// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ6lOIbDZfBsKGjJ8jD-APuizH17KSeHE',
    appId: '1:739143476771:web:2a4328cfe289454038f396',
    messagingSenderId: '739143476771',
    projectId: 'authtutorial-15fac',
    authDomain: 'authtutorial-15fac.firebaseapp.com',
    storageBucket: 'authtutorial-15fac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYxfFX2UT0euQMEQTswRMXDixw7ve9sE',
    appId: '1:739143476771:android:37a75372cfb4d17938f396',
    messagingSenderId: '739143476771',
    projectId: 'authtutorial-15fac',
    storageBucket: 'authtutorial-15fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKJ85iIudmIEXm7iNePPiYfKVxtPkQeb8',
    appId: '1:739143476771:ios:48139305861c63ed38f396',
    messagingSenderId: '739143476771',
    projectId: 'authtutorial-15fac',
    storageBucket: 'authtutorial-15fac.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKJ85iIudmIEXm7iNePPiYfKVxtPkQeb8',
    appId: '1:739143476771:ios:48139305861c63ed38f396',
    messagingSenderId: '739143476771',
    projectId: 'authtutorial-15fac',
    storageBucket: 'authtutorial-15fac.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ6lOIbDZfBsKGjJ8jD-APuizH17KSeHE',
    appId: '1:739143476771:web:e390a2ed5c6caf4d38f396',
    messagingSenderId: '739143476771',
    projectId: 'authtutorial-15fac',
    authDomain: 'authtutorial-15fac.firebaseapp.com',
    storageBucket: 'authtutorial-15fac.firebasestorage.app',
  );

}